apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb-server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: mongodb-server
  template:
    metadata:
      name: mongodb-server
      labels:
        pod: mongodb-server
    spec:
      containers:
      - name: mongodb-server
        image: mongo
        ports:
          - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongo-root-username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongo-root-password
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb-server-deployment
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017