apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongodb-server
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: mongodb-server
  template:
    metadata:
      labels:
        pod: mongodb-server
    spec:
      containers:
      - name: mongodb-server
        image: mongodb-server
        imagePullPolicy: IfNotPresent