apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb-server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: mongodb-server
  template:
    metadata:
      name: mongodb-server
      labels:
        pod: mongodb-server
    spec:
      containers:
      - name: mongodb-server
        image: mongo
        imagePullPolicy: IfNotPresent