kind: Secret
apiVersion: v1
metadata:
  name: bs-userinfo-secrets
type: Opaque
data:
  bs-userinfo-bd-username: cG9zdGdyZXMK
  bs-userinfo-bd-password: c2VjcmV0Cg==
  bs-userinfo-rabbitmq-username: c29jaWFsX2NvbW11bml0eV91c2VyCg==
  bs-userinfo-rabbitmq-password: c2VjcmV0Cg==
