apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bs-userinfo-db-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: bs-userinfo-db
  labels:
    deployment-name: bs-userinfo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      pod-name: bs-userinfo-db
  template:
    metadata:
      name: bs-userinfo-db
      labels:
        pod-name: bs-userinfo-db
    spec:
      containers:
        - name: bs-userinfo-db
          image: postgres
          ports:
            - containerPort: 5433
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bs-userinfo-secrets
                  key: bs-userinfo-bd-username
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: bs-userinfo-secrets
                  key: bs-userinfo-bd-username
            - name: POSTGRES_DB
              value: userinfo
          volumeMounts:
            - name: bs-userinfo-db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: bs-userinfo-db-data
          persistentVolumeClaim:
            claimName: bs-userinfo-db-pvc